from logging import Logger
from sqlite3 import Connection, Cursor

class Manager:
    logger: Logger
    @classmethod
    def log(cls, message: str, level: int = ...) -> None: ...
    @classmethod
    def load(cls) -> None: ...
    @classmethod
    def connected(cls) -> bool: ...
    @classmethod
    def connection(cls) -> Connection | None: ...
    @classmethod
    def cursor(cls) -> Cursor | None: ...
    @classmethod
    def connect(cls) -> None: ...
